package xyz.xenondevs.nova.world.block.material

import net.kyori.adventure.key.Key
import org.bukkit.Material
import xyz.xenondevs.nova.world.block.sound.SoundGroup
import xyz.xenondevs.nova.world.item.tool.ToolCategory
import xyz.xenondevs.nova.world.item.tool.ToolTier
import xyz.xenondevs.nova.world.item.tool.VanillaToolCategories
import xyz.xenondevs.nova.world.item.tool.VanillaToolTiers

enum class MaterialType(
    val id: String,
    val displayName: String,
    val baseMaterial: Material,
    val soundGroup: SoundGroup,
    val hardness: Double,
    val toolCategory: Set<ToolCategory>?,
    val toolTier: ToolTier?,
    val requiresToolForDrops: Boolean,
    val burnTime: Int = 0
) {
    // ============ AHŞAP TÜRLERİ ============
    OAK("oak", "Meşe", Material.OAK_PLANKS, SoundGroup.WOOD, 2.0,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false, 300),
    SPRUCE("spruce", "Ladin", Material.SPRUCE_PLANKS, SoundGroup.WOOD, 2.0,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false, 300),
    BIRCH("birch", "Huş", Material.BIRCH_PLANKS, SoundGroup.WOOD, 2.0,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false, 300),
    JUNGLE("jungle", "Orman", Material.JUNGLE_PLANKS, SoundGroup.WOOD, 2.0,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false, 300),
    ACACIA("acacia", "Akasya", Material.ACACIA_PLANKS, SoundGroup.WOOD, 2.0,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false, 300),
    DARK_OAK("dark_oak", "Koyu Meşe", Material.DARK_OAK_PLANKS, SoundGroup.WOOD, 2.0,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false, 300),
    MANGROVE("mangrove", "Mangrov", Material.MANGROVE_PLANKS, SoundGroup.WOOD, 2.0,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false, 300),
    CHERRY("cherry", "Kiraz", Material.CHERRY_PLANKS, SoundGroup.CHERRY_WOOD, 2.0,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false, 300),
    BAMBOO("bamboo", "Bambu", Material.BAMBOO_PLANKS, SoundGroup.BAMBOO_WOOD, 2.0,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false, 300),
    CRIMSON("crimson", "Kızıl", Material.CRIMSON_PLANKS, SoundGroup.NETHER_WOOD, 2.0,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false, 0),
    WARPED("warped", "Çarpık", Material.WARPED_PLANKS, SoundGroup.NETHER_WOOD, 2.0,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false, 0),

    // ============ TAŞ TÜRLERİ ============
    STONE("stone", "Taş", Material.STONE, SoundGroup.STONE, 1.5,
        setOf(VanillaToolCategories.PICKAXE), VanillaToolTiers.WOOD, true),
    COBBLESTONE("cobblestone", "Kaba Taş", Material.COBBLESTONE, SoundGroup.STONE, 2.0,
        setOf(VanillaToolCategories.PICKAXE), VanillaToolTiers.WOOD, true),
    MOSSY_COBBLESTONE("mossy_cobblestone", "Yosunlu Kaba Taş", Material.MOSSY_COBBLESTONE, SoundGroup.STONE, 2.0,
        setOf(VanillaToolCategories.PICKAXE), VanillaToolTiers.WOOD, true),
    STONE_BRICKS("stone_bricks", "Taş Tuğla", Material.STONE_BRICKS, SoundGroup.STONE, 1.5,
        setOf(VanillaToolCategories.PICKAXE), VanillaToolTiers.WOOD, true),
    MOSSY_STONE_BRICKS("mossy_stone_bricks", "Yosunlu Taş Tuğla", Material.MOSSY_STONE_BRICKS, SoundGroup.STONE, 1.5,
        setOf(VanillaToolCategories.PICKAXE), VanillaToolTiers.WOOD, true),
    CRACKED_STONE_BRICKS("cracked_stone_bricks", "Çatlak Taş Tuğla", Material.CRACKED_STONE_BRICKS, SoundGroup.STONE, 1.5,
        setOf(VanillaToolCategories.PICKAXE), VanillaToolTiers.WOOD, true),
    SMOOTH_STONE("smooth_stone", "Düz Taş", Material.SMOOTH_STONE, SoundGroup.STONE, 2.0,
        setOf(VanillaToolCategories.PICKAXE), VanillaToolTiers.WOOD, true),

    // ============ DİĞER YAPI MALZEMELERİ ============
    BRICKS("bricks", "Tuğla", Material.BRICKS, SoundGroup.STONE, 2.0,
        setOf(VanillaToolCategories.PICKAXE), VanillaToolTiers.WOOD, true),
    NETHER_BRICKS("nether_bricks", "Nether Tuğlası", Material.NETHER_BRICKS, SoundGroup.NETHER_BRICKS, 2.0,
        setOf(VanillaToolCategories.PICKAXE), VanillaToolTiers.WOOD, true),
    RED_NETHER_BRICKS("red_nether_bricks", "Kırmızı Nether Tuğlası", Material.RED_NETHER_BRICKS, SoundGroup.NETHER_BRICKS, 2.0,
        setOf(VanillaToolCategories.PICKAXE), VanillaToolTiers.WOOD, true),
    END_STONE_BRICKS("end_stone_bricks", "End Taşı Tuğlası", Material.END_STONE_BRICKS, SoundGroup.STONE, 3.0,
        setOf(VanillaToolCategories.PICKAXE), VanillaToolTiers.WOOD, true),
    PURPUR("purpur", "Purpur", Material.PURPUR_BLOCK, SoundGroup.STONE, 1.5,
        setOf(VanillaToolCategories.PICKAXE), VanillaToolTiers.WOOD, true),
    QUARTZ("quartz", "Kuvars", Material.QUARTZ_BLOCK, SoundGroup.STONE, 0.8,
        setOf(VanillaToolCategories.PICKAXE), VanillaToolTiers.WOOD, true),
    SMOOTH_QUARTZ("smooth_quartz", "Düz Kuvars", Material.SMOOTH_QUARTZ, SoundGroup.STONE, 2.0,
        setOf(VanillaToolCategories.PICKAXE), VanillaToolTiers.WOOD, true),
    PRISMARINE("prismarine", "Prismarin", Material.PRISMARINE, SoundGroup.STONE, 1.5,
        setOf(VanillaToolCategories.PICKAXE), VanillaToolTiers.WOOD, true),
    DARK_PRISMARINE("dark_prismarine", "Koyu Prismarin", Material.DARK_PRISMARINE, SoundGroup.STONE, 1.5,
        setOf(VanillaToolCategories.PICKAXE), VanillaToolTiers.WOOD, true),
    BLACKSTONE("blackstone", "Siyah Taş", Material.BLACKSTONE, SoundGroup.STONE, 1.5,
        setOf(VanillaToolCategories.PICKAXE), VanillaToolTiers.WOOD, true),
    BASALT("basalt", "Bazalt", Material.BASALT, SoundGroup.BASALT, 1.25,
        setOf(VanillaToolCategories.PICKAXE), VanillaToolTiers.WOOD, true),

    // ============ DEKORATİF ============
    WOOL("wool", "Yün", Material.WHITE_WOOL, SoundGroup.WOOL, 0.8,
        setOf(VanillaToolCategories.SHEARS), null, false, 0),
    TERRACOTTA("terracotta", "Pişmiş Toprak", Material.TERRACOTTA, SoundGroup.STONE, 1.25,
        setOf(VanillaToolCategories.PICKAXE), VanillaToolTiers.WOOD, true),
    GLASS("glass", "Cam", Material.GLASS, SoundGroup.GLASS, 0.3,
        null, null, false, 0),
    ICE("ice", "Buz", Material.ICE, SoundGroup.GLASS, 0.5,
        setOf(VanillaToolCategories.PICKAXE), null, false, 0),
    PACKED_ICE("packed_ice", "Sıkıştırılmış Buz", Material.PACKED_ICE, SoundGroup.GLASS, 0.5,
        setOf(VanillaToolCategories.PICKAXE), null, false, 0),
    BLUE_ICE("blue_ice", "Mavi Buz", Material.BLUE_ICE, SoundGroup.GLASS, 0.5,
        setOf(VanillaToolCategories.PICKAXE), null, false, 0),

    // ============ METAL ============
    IRON("iron", "Demir", Material.IRON_BLOCK, SoundGroup.METAL, 5.0,
        setOf(VanillaToolCategories.PICKAXE), VanillaToolTiers.STONE, true),
    GOLD("gold", "Altın", Material.GOLD_BLOCK, SoundGroup.METAL, 3.0,
        setOf(VanillaToolCategories.PICKAXE), VanillaToolTiers.IRON, true),
    DIAMOND("diamond", "Elmas", Material.DIAMOND_BLOCK, SoundGroup.METAL, 5.0,
        setOf(VanillaToolCategories.PICKAXE), VanillaToolTiers.IRON, true),
    NETHERITE("netherite", "Netherit", Material.NETHERITE_BLOCK, SoundGroup.NETHERITE_BLOCK, 50.0,
        setOf(VanillaToolCategories.PICKAXE), VanillaToolTiers.DIAMOND, true),
    EMERALD("emerald", "Zümrüt", Material.EMERALD_BLOCK, SoundGroup.METAL, 5.0,
        setOf(VanillaToolCategories.PICKAXE), VanillaToolTiers.IRON, true),
    LAPIS("lapis", "Lapis Lazuli", Material.LAPIS_BLOCK, SoundGroup.STONE, 3.0,
        setOf(VanillaToolCategories.PICKAXE), VanillaToolTiers.STONE, true),
    REDSTONE("redstone", "Kızıltaş", Material.REDSTONE_BLOCK, SoundGroup.STONE, 5.0,
        setOf(VanillaToolCategories.PICKAXE), VanillaToolTiers.IRON, true),
    COAL("coal", "Kömür", Material.COAL_BLOCK, SoundGroup.STONE, 5.0,
        setOf(VanillaToolCategories.PICKAXE), VanillaToolTiers.WOOD, true),

    // ============ IŞIK KAYNAKLARI ============
    GLOWSTONE("glowstone", "Işık Taşı", Material.GLOWSTONE, SoundGroup.STONE, 0.3,
        setOf(VanillaToolCategories.PICKAXE), null, false),
    SEA_LANTERN("sea_lantern", "Deniz Feneri", Material.SEA_LANTERN, SoundGroup.GLASS, 0.3,
        setOf(VanillaToolCategories.PICKAXE), null, false),
    SHROOMLIGHT("shroomlight", "Mantar Işığı", Material.SHROOMLIGHT, SoundGroup.SHROOMLIGHT, 1.0,
        setOf(VanillaToolCategories.HOE), null, false),
    JACK_O_LANTERN("jack_o_lantern", "Bal Kabağı Feneri", Material.JACK_O_LANTERN, SoundGroup.WOOD, 1.0,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false),

    // ============ YATAKLAR ============
    WHITE_BED("white_bed", "Beyaz Yatak", Material.WHITE_BED, SoundGroup.WOOD, 0.2,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false),
    ORANGE_BED("orange_bed", "Turuncu Yatak", Material.ORANGE_BED, SoundGroup.WOOD, 0.2,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false),
    MAGENTA_BED("magenta_bed", "Eflatun Yatak", Material.MAGENTA_BED, SoundGroup.WOOD, 0.2,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false),
    LIGHT_BLUE_BED("light_blue_bed", "Açık Mavi Yatak", Material.LIGHT_BLUE_BED, SoundGroup.WOOD, 0.2,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false),
    YELLOW_BED("yellow_bed", "Sarı Yatak", Material.YELLOW_BED, SoundGroup.WOOD, 0.2,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false),
    LIME_BED("lime_bed", "Açık Yeşil Yatak", Material.LIME_BED, SoundGroup.WOOD, 0.2,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false),
    PINK_BED("pink_bed", "Pembe Yatak", Material.PINK_BED, SoundGroup.WOOD, 0.2,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false),
    GRAY_BED("gray_bed", "Gri Yatak", Material.GRAY_BED, SoundGroup.WOOD, 0.2,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false),
    LIGHT_GRAY_BED("light_gray_bed", "Açık Gri Yatak", Material.LIGHT_GRAY_BED, SoundGroup.WOOD, 0.2,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false),
    CYAN_BED("cyan_bed", "Camgöbeği Yatak", Material.CYAN_BED, SoundGroup.WOOD, 0.2,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false),
    PURPLE_BED("purple_bed", "Mor Yatak", Material.PURPLE_BED, SoundGroup.WOOD, 0.2,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false),
    BLUE_BED("blue_bed", "Mavi Yatak", Material.BLUE_BED, SoundGroup.WOOD, 0.2,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false),
    BROWN_BED("brown_bed", "Kahverengi Yatak", Material.BROWN_BED, SoundGroup.WOOD, 0.2,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false),
    GREEN_BED("green_bed", "Yeşil Yatak", Material.GREEN_BED, SoundGroup.WOOD, 0.2,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false),
    RED_BED("red_bed", "Kırmızı Yatak", Material.RED_BED, SoundGroup.WOOD, 0.2,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false),
    BLACK_BED("black_bed", "Siyah Yatak", Material.BLACK_BED, SoundGroup.WOOD, 0.2,
        setOf(VanillaToolCategories.AXE), VanillaToolTiers.WOOD, false);

    val key: Key = Key.key("minecraft", id)
}
